export const dashboardStates = Object.freeze([
  "HEALTHY", "WARNING", "CRITICAL", "SENSOR FAILURE", "OFFLINE BUFFERING",
  "PROVENANCE VERIFIED", "PROVENANCE VIOLATION", "MAINTENANCE REQUIRED",
  "REPAIR VERIFIED", "RE-INSPECTION REQUIRED"
]);
